import { z } from "zod";
import { ACTOR_ROLES, CONDITION_OPERATORS, FACT_KEYS, PATIENT_FIELDS, POLICY_EFFECTS, REQUEST_PURPOSES, SEVERITIES, TOOL_NAMES, TRUTH_VALUES } from "./catalogs";

const strictObject = z.object;
const nullableString = z.string().nullable();
const dateTime = z.string().datetime({ offset: true });
const conditionValue = z.union([z.string(), z.number(), z.boolean(), z.array(z.string()), z.null()]);
const actorRole = z.enum(ACTOR_ROLES);
const toolName = z.enum(TOOL_NAMES);
const patientField = z.enum(PATIENT_FIELDS);
const policyEffect = z.enum(POLICY_EFFECTS);
const severity = z.enum(SEVERITIES);

export const ConstitutionClauseSchema = strictObject({ id: z.string(), articleNumber: z.number().int(), title: z.string(), text: z.string(), source: z.enum(["seed", "user"]), status: z.enum(["clean", "dirty", "compiling", "compiled", "error"]), lastCompiledText: nullableString }).strict();
export const PolicyConditionSchema = strictObject({ id: z.string(), fact: z.enum(FACT_KEYS), operator: z.enum(CONDITION_OPERATORS), value: conditionValue, label: z.string() }).strict();
export const PolicyRuleSchema = strictObject({ id: z.string(), sourceClauseId: z.string(), name: z.string(), description: z.string(), priority: z.number().int().min(1).max(100), appliesToTools: z.array(toolName), conditionMode: z.literal("ALL"), conditions: z.array(PolicyConditionSchema), effect: policyEffect, allowedFields: z.array(patientField), onIndeterminate: z.enum(["DENY", "REQUIRE_HUMAN_APPROVAL"]), overridesRuleIds: z.array(z.string()), severity, enabled: z.boolean() }).strict();
export const PolicyDefaultsSchema = strictObject({ noMatchingRuleForCriticalTool: z.literal("DENY"), noMatchingRuleForHighRiskTool: z.literal("REQUIRE_HUMAN_APPROVAL"), noMatchingRuleForLowRiskTool: z.literal("DENY"), equalPriorityConflict: z.literal("MOST_RESTRICTIVE"), emptyFilteredDisclosure: z.literal("DENY") }).strict();
export const PolicyBundleSchema = strictObject({ schemaVersion: z.literal(1), bundleId: z.string(), versionLabel: z.string(), rules: z.array(PolicyRuleSchema), defaults: PolicyDefaultsSchema }).strict();

export const ConstitutionVersionSchema = strictObject({ id: z.string(), label: z.string(), status: z.enum(["LEGACY_UNSAFE_BASELINE", "DRAFT", "ACTIVE", "ARCHIVED"]), createdAt: dateTime, activatedAt: nullableString, parentVersionId: nullableString, clauses: z.array(ConstitutionClauseSchema), policyBundle: PolicyBundleSchema, bundleHash: z.string(), activationTestRunId: nullableString, acknowledgedIssueIds: z.array(z.string()), changeSummary: z.string() }).strict();
export const PolicyIssueSchema = strictObject({ id: z.string(), severity, code: z.string(), title: z.string(), detail: z.string(), relatedClauseIds: z.array(z.string()), relatedRuleIds: z.array(z.string()), suggestedResolution: z.string(), acknowledged: z.boolean() }).strict();
export const CompileResultSchema = strictObject({ sourceClauseId: z.string(), normalizedClause: z.string(), interpretationSummary: z.string(), rules: z.array(PolicyRuleSchema), ambiguities: z.array(PolicyIssueSchema), assumptions: z.array(z.string()) }).strict();
export const RevisionResultSchema = strictObject({ sourceRuleIds: z.array(z.string()), instruction: z.string(), revisedRules: z.array(PolicyRuleSchema), changeSummary: z.string(), warnings: z.array(PolicyIssueSchema) }).strict();
export const PolicyFieldChangeSchema = strictObject({ field: z.enum(["name", "description", "priority", "appliesToTools", "conditions", "effect", "allowedFields", "onIndeterminate", "overridesRuleIds", "severity", "enabled"]), before: z.unknown(), after: z.unknown(), summary: z.string() }).strict();
export const PolicyRuleChangeSchema = strictObject({ ruleId: z.string(), changes: z.array(PolicyFieldChangeSchema) }).strict();
export const PolicyStructuralDiffSchema = strictObject({ addedRules: z.array(PolicyRuleSchema), removedRules: z.array(PolicyRuleSchema), changedRules: z.array(PolicyRuleChangeSchema), unchangedRuleIds: z.array(z.string()) }).strict();
export const CompilePreviewSchema = strictObject({ result: CompileResultSchema, proposedBundle: PolicyBundleSchema, analysisIssues: z.array(PolicyIssueSchema), diff: PolicyStructuralDiffSchema }).strict();
export const RevisionPreviewSchema = strictObject({ result: RevisionResultSchema, proposedBundle: PolicyBundleSchema, analysisIssues: z.array(PolicyIssueSchema), diff: PolicyStructuralDiffSchema }).strict();

export const ActorContextSchema = strictObject({ id: z.string(), displayName: z.string(), role: actorRole, identityVerified: z.boolean().nullable(), organizationVerified: z.boolean().nullable(), organizationName: nullableString }).strict();
export const EmergencyContextSchema = strictObject({ incidentId: z.string(), declared: z.boolean(), credible: z.boolean().nullable(), imminent: z.boolean().nullable(), threatToLife: z.boolean().nullable(), evidenceSource: z.enum(["self_claimed", "verified_dispatch", "hospital_system", "unavailable"]) }).strict();
export const ApprovalContextSchema = strictObject({ status: z.enum(["not_requested", "pending", "approved", "denied", "unknown"]), approverRole: actorRole.nullable(), approvalRequestId: nullableString }).strict();
export const EvaluationContextSchema = strictObject({ actor: ActorContextSchema, emergency: EmergencyContextSchema, approval: ApprovalContextSchema }).strict();
export const AgentActionSchema = strictObject({ id: z.string(), tool: toolName, actorId: z.string(), patientId: nullableString, requestedFields: z.array(patientField), recipientId: nullableString, purpose: z.enum(REQUEST_PURPOSES), message: nullableString, claimedEmergency: z.boolean(), sourceRequest: z.string(), proposalSummary: z.string() }).strict();
export const PatientRecordSchema = strictObject({ id: z.string(), fullName: z.string(), dateOfBirth: z.string(), bloodType: z.string(), criticalAllergies: z.array(z.string()), currentEmergencyMedications: z.array(z.string()), emergencyWarningFlags: z.array(z.string()), diagnoses: z.array(z.string()), homeAddress: z.string(), insuranceInformation: z.string(), emergencyContacts: z.array(strictObject({ name: z.string(), relationship: z.string(), phone: z.string() }).strict()), clinicalNotes: z.array(z.string()) }).strict();

export const ConditionResultSchema = strictObject({ ruleId: z.string(), conditionId: z.string(), fact: z.enum(FACT_KEYS), operator: z.enum(CONDITION_OPERATORS), expected: conditionValue, actual: conditionValue, result: z.enum(TRUTH_VALUES), explanation: z.string() }).strict();
export const RuleEvaluationSchema = strictObject({ ruleId: z.string(), priority: z.number().int(), state: z.enum(["MATCH", "NO_MATCH", "INDETERMINATE", "DISABLED"]), conditionResults: z.array(ConditionResultSchema), candidateEffect: policyEffect.nullable(), overridden: z.boolean(), overriddenByRuleId: nullableString }).strict();
export const TraceStepSchema = strictObject({ id: z.string(), order: z.number().int(), phase: z.enum(["REQUEST", "FACTS", "RULE_EVALUATION", "RESOLUTION", "FIELD_FILTER", "TOOL_GATE", "TOOL_EXECUTION", "AUDIT"]), status: z.enum(["info", "pass", "fail", "warning"]), title: z.string(), detail: z.string(), relatedRuleIds: z.array(z.string()) }).strict();
export const PolicyDecisionSchema = strictObject({ id: z.string(), evaluatedAt: dateTime, actionId: z.string(), bundleId: z.string(), outcome: policyEffect, reasonCode: z.string(), humanExplanation: z.string(), requestedFields: z.array(patientField), permittedFields: z.array(patientField), deniedFields: z.array(patientField), appliedRuleIds: z.array(z.string()), overriddenRuleIds: z.array(z.string()), ruleEvaluations: z.array(RuleEvaluationSchema), trace: z.array(TraceStepSchema), requiresApproval: z.boolean(), toolExecutionPermitted: z.boolean() }).strict();

export const ToolExecutionResultSchema = strictObject({ executionId: z.string(), tool: toolName, executed: z.boolean(), output: z.record(z.string(), z.unknown()).nullable(), exposedPatientFields: z.array(patientField), executedAt: dateTime.nullable() }).strict();
export const AttackScenarioSchema = strictObject({ id: z.string(), name: z.string(), description: z.string(), actorId: z.string(), patientId: z.string(), requestText: z.string(), evaluationContext: EvaluationContextSchema, fallbackAction: AgentActionSchema }).strict();
export const AttackRunSchema = strictObject({ id: z.string(), scenarioId: z.string(), constitutionVersionId: z.string(), startedAt: dateTime, completedAt: dateTime, requestText: z.string(), action: AgentActionSchema, actionSource: z.enum(["groq", "fallback", "frozen_replay"]), decision: PolicyDecisionSchema, toolResult: ToolExecutionResultSchema.nullable() }).strict();
export const RegressionTestCaseSchema = strictObject({ id: z.string(), name: z.string(), severity, scenarioId: z.string(), expectedOutcome: policyEffect, expectedPermittedFields: z.array(patientField) }).strict();
export const RegressionTestResultSchema = strictObject({ testCaseId: z.string(), passed: z.boolean(), severity, expectedOutcome: policyEffect, actualOutcome: policyEffect, expectedPermittedFields: z.array(patientField), actualPermittedFields: z.array(patientField), decisionId: z.string(), failureDetail: nullableString }).strict();
export const TestRunSchema = strictObject({ id: z.string(), constitutionVersionId: z.string(), bundleHash: z.string(), startedAt: dateTime, completedAt: dateTime, results: z.array(RegressionTestResultSchema), blockingFailureCount: z.number().int(), warningFailureCount: z.number().int() }).strict();
export const ActivationAssessmentSchema = strictObject({ canActivate: z.boolean(), schemaValid: z.boolean(), bundleHashMatchesLatestTestRun: z.boolean(), blockingReasonCodes: z.array(z.enum(["SCHEMA_INVALID", "POLICY_ISSUES", "NO_TEST_RUN", "STALE_TEST_RUN", "TEST_FAILURES", "UNACKNOWLEDGED_WARNINGS"])), blockingIssues: z.array(PolicyIssueSchema), warningIssues: z.array(PolicyIssueSchema), latestTestRunId: nullableString, blockingTestFailures: z.array(RegressionTestResultSchema), unacknowledgedWarnings: z.array(PolicyIssueSchema) }).strict();
export const AuditEventSchema = strictObject({ id: z.string(), timestamp: dateTime, type: z.enum(["WORKSPACE_RESET", "CLAUSE_EDITED", "POLICY_COMPILED", "POLICY_REVISED", "ATTACK_STARTED", "ACTION_PROPOSED", "POLICY_DECIDED", "TOOL_EXECUTED", "TOOL_BLOCKED", "APPROVAL_REQUESTED", "APPROVAL_RESOLVED", "TEST_RUN_COMPLETED", "CONSTITUTION_ACTIVATED", "WORKSPACE_EXPORTED"]), actorLabel: z.string(), constitutionVersionId: nullableString, relatedIds: z.array(z.string()), detail: z.string(), source: z.enum(["groq", "fallback", "deterministic", "user"]), integrityHash: z.string() }).strict();
export const ApprovalRequestSchema = strictObject({ id: z.string(), action: AgentActionSchema, context: EvaluationContextSchema, constitutionVersionId: z.string(), status: z.enum(["pending", "approved", "denied"]), createdAt: dateTime, resolvedAt: nullableString, resolvedByActorId: nullableString }).strict();
export const WorkspaceStateSchema = strictObject({ schemaVersion: z.literal(1), workspaceId: z.string(), activeVersionId: z.string(), draftVersionId: z.string(), versions: z.array(ConstitutionVersionSchema), attackRuns: z.array(AttackRunSchema), testRuns: z.array(TestRunSchema), approvalRequests: z.array(ApprovalRequestSchema), auditEvents: z.array(AuditEventSchema), selectedClauseId: z.string(), selectedAttackRunId: nullableString, selectedTestRunId: nullableString, demoStage: z.enum(["CONSTITUTION", "ATTACK", "INCIDENT", "AMENDMENT", "TESTING", "REPLAY", "COMPLETE"]), providerStatus: z.enum(["unknown", "configured", "live", "fallback", "error"]) }).strict();

export type ISODateTime = z.infer<typeof dateTime>;
export type EntityId = string;
export type NullableScalar = string | number | boolean | null;
export type ConditionExpectedValue = z.infer<typeof conditionValue>;
export type ConstitutionClause = z.infer<typeof ConstitutionClauseSchema>;
export type ConstitutionVersion = z.infer<typeof ConstitutionVersionSchema>;
export type PolicyCondition = z.infer<typeof PolicyConditionSchema>;
export type PolicyRule = z.infer<typeof PolicyRuleSchema>;
export type PolicyDefaults = z.infer<typeof PolicyDefaultsSchema>;
export type PolicyBundle = z.infer<typeof PolicyBundleSchema>;
export type PolicyIssue = z.infer<typeof PolicyIssueSchema>;
export type CompileResult = z.infer<typeof CompileResultSchema>;
export type RevisionResult = z.infer<typeof RevisionResultSchema>;
export type PolicyDiffField = z.infer<typeof PolicyFieldChangeSchema>["field"];
export type PolicyFieldChange = z.infer<typeof PolicyFieldChangeSchema>;
export type PolicyRuleChange = z.infer<typeof PolicyRuleChangeSchema>;
export type PolicyStructuralDiff = z.infer<typeof PolicyStructuralDiffSchema>;
export type CompilePreview = z.infer<typeof CompilePreviewSchema>;
export type RevisionPreview = z.infer<typeof RevisionPreviewSchema>;
export type ActorContext = z.infer<typeof ActorContextSchema>;
export type EmergencyContext = z.infer<typeof EmergencyContextSchema>;
export type ApprovalContext = z.infer<typeof ApprovalContextSchema>;
export type EvaluationContext = z.infer<typeof EvaluationContextSchema>;
export type AgentAction = z.infer<typeof AgentActionSchema>;
export type PatientRecord = z.infer<typeof PatientRecordSchema>;
export type ConditionResult = z.infer<typeof ConditionResultSchema>;
export type RuleEvaluation = z.infer<typeof RuleEvaluationSchema>;
export type TraceStep = z.infer<typeof TraceStepSchema>;
export type PolicyDecision = z.infer<typeof PolicyDecisionSchema>;
export type ToolExecutionResult = z.infer<typeof ToolExecutionResultSchema>;
export type AttackScenario = z.infer<typeof AttackScenarioSchema>;
export type AttackRun = z.infer<typeof AttackRunSchema>;
export type RegressionTestCase = z.infer<typeof RegressionTestCaseSchema>;
export type RegressionTestResult = z.infer<typeof RegressionTestResultSchema>;
export type TestRun = z.infer<typeof TestRunSchema>;
export type ActivationAssessment = z.infer<typeof ActivationAssessmentSchema>;
export type AuditEvent = z.infer<typeof AuditEventSchema>;
export type ApprovalRequest = z.infer<typeof ApprovalRequestSchema>;
export type WorkspaceState = z.infer<typeof WorkspaceStateSchema>;
