"use client";

import { ArrowRight, Check, ChevronDown, LockKeyhole, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";

import { useAuth } from "../../auth/auth-provider";
import { AuthPanel } from "../auth/auth-panel";

const story = [
  { index: "01", label: "Author", title: "Give policy a human shape.", copy: "Write the rule in plain language, with the nuance and intent that prompts usually lose.", mark: "A" },
  { index: "02", label: "Test", title: "Try the awkward question.", copy: "Run adversarial and regression scenarios before the policy governs an agent.", mark: "T" },
  { index: "03", label: "Enforce", title: "Put a typed gate at the tool.", copy: "Deterministic code decides whether to allow, deny, filter, or ask for approval.", mark: "E" },
  { index: "04", label: "Audit", title: "Leave a trail someone can read.", copy: "Show the proposal, the rule path, and the outcome without hiding behind model mystique.", mark: "A" },
] as const;

export function ArticleZeroLanding() {
  const { status } = useAuth();
  const router = useRouter();
  const [authOpen, setAuthOpen] = useState(false);
  const openWorkspace = () => { if (status === "authenticated") router.push("/workspace"); else setAuthOpen(true); };

  return <main className="az-landing">
    <a className="az-skip-link" href="#landing-main">Skip to main content</a>
    <nav className="az-landing-nav" aria-label="Main navigation"><a className="az-landing-brand" href="#landing-main" aria-label="Article Zero home"><span className="az-landing-seal" aria-hidden="true">0</span><span><strong>Article Zero</strong><small>Policy with a backbone</small></span></a><div className="az-landing-links"><a href="#how-it-works">How it works</a><a href="#why-it-matters">Why it matters</a><button className="az-landing-signin" type="button" onClick={openWorkspace}>{status === "authenticated" ? "Open workspace" : "Sign in"}<ArrowRight size={14} aria-hidden="true" /></button></div></nav>
    <section className="az-landing-hero" id="landing-main" aria-labelledby="landing-title"><div className="az-landing-hero-copy"><p className="az-landing-kicker"><span className="az-landing-kicker-line" aria-hidden="true" />Constitutional controls for AI agents</p><h1 id="landing-title">Policy that can <em>say no</em> when the stakes are high.</h1><p className="az-landing-lede">Article Zero turns plain-language policy into a tested boundary at the tool call—so an agent can interpret the intent without owning the final decision.</p><div className="az-landing-actions"><button className="az-button az-button-primary az-landing-primary" type="button" onClick={openWorkspace}>Open the policy workspace<ArrowRight size={17} aria-hidden="true" /></button><a className="az-text-link" href="#how-it-works">See the four-part method <ChevronDown size={15} aria-hidden="true" /></a></div><div className="az-landing-proof"><span><Check size={14} aria-hidden="true" />Typed rules</span><span><Check size={14} aria-hidden="true" />Regression-gated</span><span><Check size={14} aria-hidden="true" />Auditable</span></div></div><div className="az-landing-hero-art" aria-label="A policy moves from intent through a deterministic enforcement gate to an audit record"><div className="az-orbit az-orbit-outer" aria-hidden="true" /><div className="az-orbit az-orbit-inner" aria-hidden="true" /><div className="az-hero-seal" aria-hidden="true">AZ<span>0</span></div><div className="az-hero-node az-hero-node-intent"><small>human intent</small><strong>“minimum necessary”</strong></div><div className="az-hero-node az-hero-node-rule"><small>compiled rule</small><strong>ALLOW + FILTER</strong></div><div className="az-hero-node az-hero-node-audit"><small>proof</small><strong>trace / 014</strong></div><div className="az-signal az-signal-one" aria-hidden="true" /><div className="az-signal az-signal-two" aria-hidden="true" /></div></section>
    <section className="az-landing-ribbon" aria-label="Product promise"><span>Human policy</span><i aria-hidden="true" /><span>Typed controls</span><i aria-hidden="true" /><span>Deterministic outcome</span><i aria-hidden="true" /><span>Readable proof</span></section>
    <section className="az-landing-story" id="how-it-works" aria-labelledby="story-title"><div className="az-landing-section-intro"><p className="az-landing-kicker">A smaller distance between intent and action</p><h2 id="story-title">A policy is only real when it survives the edge case.</h2><p>Article Zero keeps the important distinctions visible: what a person wrote, what a model proposed, and what the enforcement gate actually allowed.</p></div><div className="az-method-grid">{story.map((step) => <article className="az-method-card" key={step.label}><div className="az-method-top"><span>{step.index}</span><span className="az-method-mark" aria-hidden="true">{step.mark}</span></div><p className="az-method-label">{step.label}</p><h3>{step.title}</h3><p>{step.copy}</p><span className="az-method-rule" aria-hidden="true" /></article>)}</div></section>
    <section className="az-landing-problem" id="why-it-matters" aria-labelledby="problem-title"><div><p className="az-landing-kicker">Why it matters</p><h2 id="problem-title">Prompts can explain a boundary. They cannot be the boundary.</h2></div><div className="az-problem-copy"><p>Agent systems operate in the messy space between a request and an action. That is where a persuasive sentence, a missing field filter, or an unverifiable identity becomes a real risk.</p><p>Article Zero gives teams a calm place to author the intent, pressure-test the exceptions, and require deterministic code to make the final call.</p><button className="az-text-link" type="button" onClick={openWorkspace}>Build your first policy boundary <ArrowRight size={15} aria-hidden="true" /></button></div></section>
    <section className="az-trust-section" aria-labelledby="trust-title"><div className="az-trust-heading"><p className="az-landing-kicker">Technical trust</p><h2 id="trust-title">Two jobs. Deliberately kept apart.</h2></div><div className="az-trust-grid"><article><div className="az-trust-icon"><Sparkles size={18} aria-hidden="true" /></div><p className="az-method-label">Interpretation</p><h3>Groq interprets the human policy.</h3><p>It can help compile a clause into structured controls and surface a useful proposal. Its output is labeled, validated, and reviewable.</p><span className="az-trust-tag">proposal / never the gate</span></article><div className="az-trust-divider" aria-hidden="true"><ArrowRight size={18} /></div><article><div className="az-trust-icon az-trust-icon-solid"><ShieldCheck size={18} aria-hidden="true" /></div><p className="az-method-label">Enforcement</p><h3>Deterministic code makes the call.</h3><p>The policy engine evaluates facts, resolves conflicts, filters fields, and blocks protected tool actions when the rule says no.</p><span className="az-trust-tag">outcome / reproducible</span></article></div><p className="az-trust-footnote"><LockKeyhole size={14} aria-hidden="true" /> Every workspace is private to its signed-in Firebase account. The current hospital scenario is synthetic.</p></section>
    <section className="az-landing-cta" aria-labelledby="cta-title"><div><p className="az-landing-kicker">Make the boundary visible</p><h2 id="cta-title">Write the rule. Test the pressure. See what holds.</h2></div><button className="az-button az-button-primary az-landing-primary" type="button" onClick={openWorkspace}>{status === "authenticated" ? "Open Article Zero" : "Start with a private workspace"}<ArrowRight size={17} aria-hidden="true" /></button></section>
    <footer className="az-landing-footer"><span>Article Zero / Constitutional policy workspace</span><span>All sample identities and records are fictional. Not for clinical use.</span></footer>
    {authOpen ? <div className="az-auth-overlay" role="dialog" aria-modal="true" aria-label="Sign in to Article Zero"><AuthPanel onClose={() => setAuthOpen(false)} /></div> : null}
  </main>;
}
